# Use https://travis-ci.org/ for automatic tests

# speed up testing https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# This is a java project
language: java

script: mvn compile test

# We run on 8
jdk: [oraclejdk8]
